[package]
name = "dev"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "nestri-test-server"
path = "src/main.rs"

[dependencies]
webrtc = "0.11.0"
tokio = { version = "1.41.1", features = ["full"] }
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1.0.215", features = ["derive"]}
serde_json = "1.0.133"

